import os
import urllib.request
import base64
import fitz  # PyMuPDF

icons = {
    "copy": "copy.svg",
    "trash": "trash-2.svg",
    "refresh": "rotate-cw.svg",
    "save": "save.svg",
    "plus": "plus.svg",
    "eye": "eye.svg",
    "eye_off": "eye-off.svg",
    "key": "key-round.svg",
    "search": "search.svg",
    "shield": "shield-check.svg",
    "settings": "settings.svg",
    "lock": "lock.svg",
    "unlock": "lock-open.svg",
    "database": "database.svg",
    "folder": "folder-open.svg",
    "user": "user.svg",
    "keyboard": "keyboard.svg",
    "check": "check-circle-2.svg",
    "globe": "globe.svg",
    "chevron_up": "chevron-up.svg",
    "chevron_down": "chevron-down.svg",
    "xmark": "x.svg"
}

os.makedirs("assets/icons", exist_ok=True)
base64_dict = {}

for key, svg_name in icons.items():
    url = f"https://unpkg.com/lucide-static@latest/icons/{svg_name}"
    print(f"Downloading {key} from {url}...")
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=10) as resp:
        svg_content = resp.read().decode('utf-8')
    
    # Save SVG
    with open(f"assets/icons/{key}.svg", "w", encoding="utf-8") as f:
        f.write(svg_content)
    
    # In Lucide SVGs, stroke="currentColor". Replace currentColor with white #FFFFFF for base icon
    svg_white = svg_content.replace('stroke="currentColor"', 'stroke="#FFFFFF"')
    
    # Render to 32x32 high-resolution transparent PNG with PyMuPDF
    doc = fitz.open(stream=svg_white.encode('utf-8'), filetype='svg')
    pix = doc[0].get_pixmap(alpha=True, dpi=96)
    png_path = f"assets/icons/{key}.png"
    pix.save(png_path)
    print(f"Rendered {png_path}: {pix.width}x{pix.height}")
    
    with open(png_path, "rb") as pf:
        b64 = base64.b64encode(pf.read()).decode('ascii')
        base64_dict[key] = b64

# Generate IconResources.cs
cs_lines = [
    "// <auto-generated>",
    "// Embedded Lucide open-source icon pack (ISC/MIT license - https://lucide.dev)",
    "// </auto-generated>",
    "using System;",
    "using System.Collections.Generic;",
    "using System.Drawing;",
    "using System.IO;",
    "",
    "namespace PasswordGui",
    "{",
    "    public static class IconResources",
    "    {",
    "        private static readonly Dictionary<string, Bitmap> Cache = new Dictionary<string, Bitmap>();",
    "",
    "        public static Bitmap GetIcon(string name)",
    "        {",
    "            if (string.IsNullOrEmpty(name)) return null;",
    "            if (Cache.ContainsKey(name)) return Cache[name];",
    "",
    "            string b64 = GetBase64(name);",
    "            if (string.IsNullOrEmpty(b64)) return null;",
    "",
    "            byte[] bytes = Convert.FromBase64String(b64);",
    "            using (MemoryStream ms = new MemoryStream(bytes))",
    "            {",
    "                Bitmap bmp = new Bitmap(ms);",
    "                Cache[name] = bmp;",
    "                return bmp;",
    "            }",
    "        }",
    "",
    "        private static string GetBase64(string name)",
    "        {",
    "            switch (name.ToLowerInvariant())",
    "            {"
]

for key, b64 in base64_dict.items():
    cs_lines.append(f'                case "{key}": return "{b64}";')

cs_lines.extend([
    '                default: return null;',
    "            }",
    "        }",
    "    }",
    "}"
])

with open("IconResources.cs", "w", encoding="utf-8") as f:
    f.write("\n".join(cs_lines))

print("Generated IconResources.cs successfully with all icons!")
